Uploading files

diff --git a/.github/workflows/manual-test.yml b/.github/workflows/manual-test.yml
--- a/.github/workflows/manual-test.yml
+++ b/.github/workflows/manual-test.yml
@@ -1,14 +1,11 @@
-name: Jaya Subang flow (gather-branch)
+name: Manual test
 
 on:
   workflow_dispatch: # manual trigger ability
-  schedule:
-    # Run every day at (x:x AM PM UTC)
-    - cron: '36 23 * * *' 
 
 jobs:
   setup:
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-slim
     permissions:
       contents: write # Grant write permissions for pushing changes
     
@@ -26,7 +23,7 @@ jobs:
           echo "Python version"
           python -V
           echo "IP address"
-          curl --no-progress-meter https://ipinfo.io/ip
+          curl --no-progress-meter https://api.ipify.org
           
       - name: Update package lists
         run: |
@@ -41,36 +38,31 @@ jobs:
             linux-tools-common \
             linux-libc-dev \
             p7zip-full
-              
-      - name: Unzip gather-jaya and settings files
+             
+      - name: Unzip gather-lotus, categories, and reqs
         run: |
-          7z x runner-src/gather-jaya-src.7z -p${{ secrets.ZIP_PW }}
-          cp -v runner-src/jaya_subang_settings* .
-          cp -v runner-src/jaya_requirements.txt .
-
-      - name: Random delay
-        run: |
-          DELAY=$((RANDOM % 9))   # Random number between 0 and 8
-          echo "Random sleep for $DELAY seconds..."
-          sleep $DELAY
+          7z x runner-src/gather-lotus-src.7z -p${{ secrets.ZIP_PW }}
+          cp -v runner-src/lotus_categories* .
+          cp -v runner-src/requirements.txt .
 
       - name: pip install
-        run: pip install -r jaya_requirements.txt
+        run: pip install -r requirements.txt
           
       - name: Run script
         run: |
-          echo "Install playwright chromium"
-          python -m playwright install --with-deps --only-shell > /dev/null
-          echo "running scripts"
-          python jaya_pwright_2026_022_one_thread_arg.py -s jaya_subang_settings_1.json &
+          python lotus_from_api_args_030.py -c lotus_categories_1.json -o lotus-from-api-part1.csv &
           sleep 1
-          python jaya_pwright_2026_022_one_thread_arg.py -s jaya_subang_settings_2.json
+          python lotus_from_api_args_030.py -c lotus_categories_2.json -o lotus-from-api-part2.csv &
+          sleep 1
+          python lotus_from_api_args_030.py -c lotus_categories_3.json -o lotus-from-api-part3.csv
           wait
           echo "Scripts done."
+          echo "Error log:"
+          cat lotus_error_log.txt
 
-      - name: Validate output file
+      - name: Validate output files
         run: |
-          FILES=("jaya_subang_one_thread_1.csv" "jaya_subang_one_thread_2.csv")
+          FILES=("lotus-from-api-part1.csv" "lotus-from-api-part2.csv" "lotus-from-api-part3.csv")
           for FILE in "${FILES[@]}"; do
             echo "Checking if $FILE exists and is larger than 100 KB..."
             if [ ! -f "$FILE" ]; then
@@ -89,8 +81,8 @@ jobs:
       - name: Run processing script
         run: |
           echo "running processing script"
-          python jaya_subang_fixer_01.py
- 
+          python lotus_fixer_036_concat.py
+
       - name: Set up Git
         run: |
           git config --global user.name "github-actions[bot]"
@@ -99,13 +91,15 @@ jobs:
       - name: Pull latest changes before push
         run: |
           git pull origin gather-branch --rebase
-    
+          git push origin gather-branch
+
       - name: Commit and push generated files
         run: |
           mkdir -p raw_data
-          cp jaya_subang_one* raw_data/
-          cp jaya_subang-output* raw_data/
-          git add raw_data/jaya_subang_one*
-          git add raw_data/jaya_subang-output*
-          git commit -m "Automated: Add generated Jaya Subang files" || echo "No changes to commit"
-          git push origin gather-branch      
+          cp lotus-from-api* raw_data/
+          cp lotus-output* processed/
+          cp lotus_error_log.txt raw_data/
+          git add raw_data/lotus*
+          git add processed/lotus*
+          git commit -m "Automated: Add generated Lotus files" || echo "No changes to commit"
+          git push origin gather-branch    
